CREATE TABLE audit_logs
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status                VARCHAR(255),
    last_folder_processed VARCHAR(255),
    files_processed       TEXT[],
    start_date            TIMESTAMP WITHOUT TIME ZONE,
    end_date              TIMESTAMP WITHOUT TIME ZONE,
    time_spent_in_hours   BIGINT,
    error                 VARCHAR(255),
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);