CREATE TABLE audit_logs
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status                     VARCHAR(255),
    last_folder_processed      VARCHAR(255),
    current_file_name          VARCHAR(255),
    files_processed            TEXT[],
    records_inserted           BIGINT,
    start_date                 TIMESTAMP WITHOUT TIME ZONE,
    end_date                   TIMESTAMP WITHOUT TIME ZONE,
    last_heartbeat             TIMESTAMP WITHOUT TIME ZONE,
    number_of_times_it_stopped INTEGER,
    total_time_spent_in_ms     BIGINT,
    error                      TEXT,
    CONSTRAINT pk_audit_logs PRIMARY KEY (id)
);